# Generated by Django 3.1 on 2020-11-18 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contato_mostrar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='tipo',
        ),
    ]
